"""
Prompt runner interface — separates testing from optimization (ISP).

This module defines the ``IPromptRunner`` abstraction: the contract for any
service that can *execute* a prompt template by rendering it with runtime
variables and forwarding the result to an LLM.

Interface Segregation Principle (ISP) in practice
--------------------------------------------------
Running a prompt, evaluating a prompt, and optimizing a prompt are three
distinct capabilities.  Rather than lumping them into one monolithic
interface, the PromptOps Framework splits them into ``IPromptRunner``,
``IEvaluator``, and ``IOptimizer``.  This means:

* A component that only *runs* prompts never has to know about metrics.
* A component that only *evaluates* outputs never depends on an LLM client.
* Each interface can evolve independently without breaking the others.

The interface is ``async`` because prompt execution involves a network call
to the LLM provider — keeping it non-blocking is essential for responsive
APIs and UIs.
"""

from abc import ABC, abstractmethod
from typing import Any


class IPromptRunner(ABC):
    """Abstract interface for executing prompt templates against an LLM.

    Implementations are responsible for two steps:
    1. **Rendering** — substitute ``{placeholders}`` in the template with the
       supplied variables.
    2. **Completion** — send the rendered prompt to an LLM and return its
       response.

    Consumers depend on this abstraction rather than a concrete runner,
    following the **Dependency Inversion Principle (DIP)**.
    """

    @abstractmethod
    async def run(
        self, prompt_template: str, variables: dict[str, str], **kwargs: Any
    ) -> str:
        """Render *prompt_template* with *variables* and return the LLM response.

        Parameters
        ----------
        prompt_template : str
            A string containing ``{placeholder}`` tokens, e.g.
            ``"Translate '{text}' to {language}."``.
        variables : dict[str, str]
            Mapping of placeholder names to their runtime values.
        **kwargs : Any
            Extra options forwarded to the underlying LLM client.

        Returns
        -------
        str
            The text generated by the language model.
        """
        ...
